In [4]:
#this file is used for generate the forward kinematics for UR3 (We can use this to get T06 and d06)
import numpy as np
from scipy.linalg import expm

"""
Use 'expm' for matrix exponential.
Angles are in radian, distance are in meters.
"""

def Get_MS():
    # =================== Your code starts here ====================#
    # Fill in the correct values for S1~6, as well as the M matrix
    M = [[0,-1,0,0.39],[0,0,-1,0.401],[1,0,0,0.2155],[0,0,0,1]]
    S = np.zeros((6,6))
    w1=[0,0,1]
    q1=[-0.15,0.15,0.01]
    v1=-np.cross(w1,q1)
    w2=[0,1,0]
    q2=[-0.15,0.27,0.162]
    v2=-np.cross(w2,q2)
    w3=[0,1,0]
    q3=[0.094,0.27,0.162]
    v3=-np.cross(w3,q3)
    w4=[0,1,0]
    q4=[0.307,0.177,0.162]
    v4=-np.cross(w4,q4)
    w5=[1,0,0]
    q5=[0.307,0.26,0.162]
    v5=-np.cross(w5,q5)
    w6=[0,1,0]
    q6=[0.39,0.26,0.162]
    v6=-np.cross(w6,q6)
    S=[[w1[0],w2[0],w3[0],w4[0],w5[0],w6[0]],
       [w1[1],w2[1],w3[1],w4[1],w5[1],w6[1]],
       [w1[2],w2[2],w3[2],w4[2],w5[2],w6[2]],
       [v1[0],v2[0],v3[0],v4[0],v5[0],v6[0]],
       [v1[1],v2[1],v3[1],v4[1],v5[1],v6[1]],
       [v1[2],v2[2],v3[2],v4[2],v5[2],v6[2]]]    
       
       


    # ==============================================================#
    return M, S

def braket_s(s): #function for transform the s vector to the braket form [s]
    w=s[0:3]
    v=s[3:6]
    return [[0,-w[2],w[1],v[0]],[w[2],0,-w[0],v[1]],[-w[1],w[0],0,v[2]],[0,0,0,0]]

"""
Function that calculates encoder numbers for each motor
"""
def lab_fk(theta1, theta2, theta3, theta4, theta5, theta6):

    # Initialize the return_value 
    return_value = [None, None, None, None, None, None]

    # =========== Implement joint angle to encoder expressions here ===========
    print("Foward kinematics calculated:\n")

    # =================== Your code starts here ====================#
    M, S = Get_MS()
    s1=[S[0][0],S[1][0],S[2][0],S[3][0],S[4][0],S[5][0]]
    s2=[S[0][1],S[1][1],S[2][1],S[3][1],S[4][1],S[5][1]]
    s3=[S[0][2],S[1][2],S[2][2],S[3][2],S[4][2],S[5][2]]
    s4=[S[0][3],S[1][3],S[2][3],S[3][3],S[4][3],S[5][3]]
    s5=[S[0][4],S[1][4],S[2][4],S[3][4],S[4][4],S[5][4]]
    s6=[S[0][5],S[1][5],S[2][5],S[3][5],S[4][5],S[5][5]]
    brs1=braket_s(s1)#change the s to the bracket form
    brs2=braket_s(s2)
    brs3=braket_s(s3)
    brs4=braket_s(s4)
    brs5=braket_s(s5)
    brs6=braket_s(s6)
ra1=np.dot(brs1,dtor(theta1))
#before dot the [s] and theta, transform the theta to radius unit
    ra2=np.dot(brs2,dtor(theta2))
    ra3=np.dot(brs3,dtor(theta3))
    ra4=np.dot(brs4,dtor(theta4))
    ra5=np.dot(brs5,dtor(theta5))
    ra6=np.dot(brs6,dtor(theta6))
    t0=np.dot(expm(ra1),expm(ra2))
    t1=np.dot(t0,expm(ra3))
    t2=np.dot(t1,expm(ra4))
    t3=np.dot(t2,expm(ra5))
    t4=np.dot(t3,expm(ra6))
    T=np.dot(t4,M)# the T06
    
        





    print('\nd06 is\n',[T[0][3],T[1][3],T[2][3]]) #the d06
    print('\nx={},y={},z={}\n'.format(T[0][3],T[1][3],T[2][3]))
    # ==============================================================#
    
    print(str(T) + "\n")

    return_value[0] = theta1 + 180
    return_value[1] = theta2
    return_value[2] = theta3
    return_value[3] = theta4 - (0.5*180)
    return_value[4] = theta5
    return_value[5] = theta6
    return return_value

def dtor(theta):#change the unit of angle from degree to radius
    return theta*np.pi/180


IndentationError: unexpected indent (<ipython-input-4-2d1db3f0baeb>, line 78)

In [5]:
lab_fk(-40,-50,75,-30,-90,0) #inputs should be radius

Foward kinematics calculated:


d06 is
 [0.29587589599454656, -0.010700208074035725, 0.12566762858738095]

x=0.29587589599454656,y=-0.010700208074035725,z=0.12566762858738095

[[ 0.64278761 -0.76312941 -0.06676517  0.2958759 ]
 [ 0.76604444  0.64034161  0.05602263 -0.01070021]
 [ 0.         -0.08715574  0.9961947   0.12566763]
 [ 0.          0.          0.          1.        ]]



[140, -50, 75, -120.0, -90, 0]

In [6]:
print('verified')

verified


In [7]:
print('The answer for the configuration 1:\n')
lab_fk(35,-35,25,-20,-90,0) 

The answer for the configuration 1:

Foward kinematics calculated:


d06 is
 [0.2084063186135264, 0.6005554512976803, 0.2583301303791055]

x=0.2084063186135264,y=0.6005554512976803,z=0.2583301303791055

[[-0.57357644 -0.70940648 -0.40957602  0.20840632]
 [ 0.81915204 -0.49673176 -0.28678822  0.60055545]
 [ 0.         -0.5         0.8660254   0.25833013]
 [ 0.          0.          0.          1.        ]]



[215, -35, 25, -110.0, -90, 0]

In [8]:
print('The answer for the configuration 2:\n')
lab_fk(10,-25,35,-45,-90,10) 

The answer for the configuration 2:

Foward kinematics calculated:


d06 is
 [0.4002031999186513, 0.41221259632522367, 0.1655668269005536]

x=0.4002031999186513,y=0.41221259632522367,z=0.1655668269005536

[[-0.03092682 -0.82460528 -0.56486252  0.4002032 ]
 [ 0.99454677  0.03092682 -0.0996005   0.4122126 ]
 [ 0.0996005  -0.56486252  0.81915204  0.16556683]
 [ 0.          0.          0.          1.        ]]



[190, -25, 35, -135.0, -90, 10]